services:

  redis:
    image: redis:alpine
    container_name: redis_cache
    ports:
      - "6379:6379"
    networks:
      - numerology_network

  postgres:
    image: postgres:latest
    container_name: postgres_db
    env_file:
      - ./backend/.env
  environment:
    POSTGRES_USER: ${POSTGRES_USER}
    POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    POSTGRES_DB: ${POSTGRES_DB}

    volumes:
      - ./db_data:/var/lib/postgresql/data
    networks:
      - numerology_network

  web:
    build:
      context: ./backend
    container_name: web
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/code
    restart: on-failure:2
    depends_on:
      - postgres
      - redis
    networks:
      - numerology_network
    env_file:
      - ./backend/.env

  nginx:
    build:
      context: ./frontend
    container_name: nginx_proxy
    ports:
      - "80:80"
    volumes:
      - ./static:/usr/share/nginx/html
    depends_on:
      - web
    restart: on-failure:2
    networks:
      - numerology_network

networks:
  numerology_network:
    driver: bridge
